name-template: 'Eyes_Protection_Reminder_v$NEXT_PATCH_VERSION 👀'
tag-template: v$NEXT_PATCH_VERSION
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🤬 Bugs'
    labels:
      - 'bug'
      - 'fix'
      - 'bugfix'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
prerelease: false

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: [`$PREVIOUS_TAG...v$NEXT_PATCH_VERSION`](https://github.com/hardingadonis/Eyes_Protection_Reminder/compare/$PREVIOUS_TAG...v$NEXT_PATCH_VERSION)

  ## Contributors

  $CONTRIBUTORS

  ## Previous Release

  - [Eyes_Protection_Reminder_$PREVIOUS_TAG](https://github.com/hardingadonis/Eyes_Protection_Reminder/releases/tag/$PREVIOUS_TAG)