name: Build file

on: 
  push:
    branches: [main, develop]

jobs:
  build: 
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      # - uses: syphar/restore-virtualenv@v1
      #   id: cache-virtualenv
      #   with:
      #     requirement_files: requirements.txt  # this is optional

      # - uses: syphar/restore-pip-download-cache@v1
      #   if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - run: pip install -r requirements.txt
        # if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - name: Build file
        run: py -m pyinstaller --noconfirm --onefile --windowed --icon "assets/icon_white.ico" --name "Eyes Protection Reminder" --add-data "D:/Learning/Python/Eyes_Protection_Reminder/assets;assets/"  "main.py"