name: Build Project

on: [push, pull_request]

jobs:
  build:
    name: Build Project
    runs-on: windows-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Setup MSVC Developer Command Prompt
      uses: TheMrMilchmann/setup-msvc-dev@v2.0.0
      with:
        arch: x64
        version: 1.11.1

    - name: Install Ninja build tool
      uses: seanmiddleditch/gha-setup-ninja@v3
    
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug -DwxUSE_STL=ON -DwxBUILD_COMPATIBILITY="3.1" -DwxBUILD_SHARED=OFF -G"Ninja" -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl
    
    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config Debug --target EPR