name: Build Project

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Project
    runs-on: windows-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build
    
    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake .. -DwxBUILD_SHARED=OFF -G"Visual Studio 17 2022" -Ax64
    
    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build .