name: Build Project

on: push

jobs:
  build:
    name: Build Project
    runs-on: windows-2022

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2.5.0
      with:
        submodules: recursive
        
    - name: Install Ninja build tool
      uses: seanmiddleditch/gha-setup-ninja@v3
    
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
        cmake .. -DCMAKE_BUILD_TYPE=Debug -DwxUSE_STL=ON -DwxBUILD_COMPATIBILITY="3.1" -DwxBUILD_SHARED=OFF -G"Ninja" -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl
    
    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config Debug