name: Lastest Release

on:
  push:
    branches: [test-ci-cd]

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    name: Update Release Draft
    runs-on: ubuntu-latest

    outputs:
      tag_name: ${{ steps.create_draft_release.tag_name }}

    steps:
    - name: Create New Draft
      id: create_draft_release
      uses: release-drafter/release-drafter@v5.21.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Release.Windows.${{ matrix.architecture }}.${{ needs.update_release_draft.create_draft_release.outputs.tag_name }}
    needs: update_release_draft
    runs-on: windows-latest
  
    strategy:
      fail-fast: false
      matrix:
        architecture: [x86, x64]