name: Lastest Release

on:
  push:
    branches: [switch_to_cpp]

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: windows-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build
    
    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake .. -DCMAKE_BUILD_TYPE=MinSizeRel -DwxBUILD_SHARED=OFF -G"Visual Studio 17 2022" -Ax64
    
    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config MinSizeRel
    
    - name: Zip executable files
      uses: papeloto/action-zip@v1
      with:
        files: ${{github.workspace}}/build/MinSizeRel/EPR.exe
        dest: Eyes_Protection_Reminder_v4.0.0.zip
    
    - name: Public release files
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{secrets.GITHUB_TOKEN}}"
        automatic_release_tag: "v4.x.x"
        prerelease: false
        title: "Eyes_Protection_Reminder_v4.0.0"
        files: Eyes_Protection_Reminder_v4.0.0.zip
