name: Lastest Release

on:
  push:
    branches: [main]

jobs:
  release:
    name: "Lastest Release"
    runs-on: windows-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}\build
    
    - name: Configure CMake
      working-directory: ${{github.workspace}}\build
      run: cmake .. -DCMAKE_BUILD_TYPE=MinSizeRel -DwxUSE_STL=ON -DwxBUILD_COMPATIBILITY=3.1 -DwxBUILD_SHARED=OFF -G"Visual Studio 17 2022" -Ax64
    
    - name: Build
      working-directory: ${{github.workspace}}\build
      run: cmake --build . --config MinSizeRel
    
    - name: Zip executable files
      uses: TheDoctor0/zip-release@0.6.2
      with:
        type: "zip"
        filename: "Eyes_Protection_Reminder_v4.1.0.zip"
        path: ${{github.workspace}}\build\source\MinSizeRel\Eyes_Protection_Reminder_v4.1.0.exe
    
    - name: Public release files
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{secrets.GITHUB_TOKEN}}"
        automatic_release_tag: "v4.1.x"
        prerelease: true
        title: "Eyes_Protection_Reminder_v4.1.0"
        files: Eyes_Protection_Reminder_v4.1.0.zip
