name: pre release

on:
  push:
    branches: [main]

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - run: pip install -r requirements.txt

      - name: Build file
        run: pyinstaller --noconfirm --onefile --windowed --icon "assets/icon.ico" --name "Eyes_Protection_Reminder_v3.0.0" --add-data "./assets;assets/"  "src/main.py"
      
      - uses: svenstaro/upx-action@v2
        with:
            file: |
              Eyes_Protection_Reminder_v3.0.0.exe
            args: --best
      
      - uses: papeloto/action-zip@v1
        with:
            files: dist/
            dest: Eyes_Protection_Reminder_v3.0.0.zip

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v3.x.x"
          prerelease: true
          title: "Eyes_Protection_Reminder v3.0.0"
          files: |
            *.zip