name: Lastest Release

on:
  push:
    branches: [test-ci-cd]

jobs:
  build:
    name: Release.Windows.${{ matrix.architecture }}
    runs-on: windows-latest
  
    strategy:
      fail-fast: false
      matrix:
      - { architecture = x86 }
      - { architecture = x64 }
    
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Setup MSVC Developer Command Prompt
      uses: TheMrMilchmann/setup-msvc-dev@v2.0.0
      with:
        arch: ${{ matrix.architecture }}
    
    - name: Install Ninja build tool
      with:
        version: 1.11.1
    
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=MinSizeRel -DwxUSE_STL=ON -DwxBUILD_COMPATIBILITY="3.1" -DwxBUILD_SHARED=OFF -G"Ninja" -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl
    
    - name: Build Project
      working-directory: ${{ github.workspace }}\build
      run: cmake --build . --config MinSizeRel --target EPR
    
    - name: Zip executable files
      uses: TheDoctor0/zip-release@0.6.2
      with:
        type: zip
        filename: Eyes_Protection_Reminder_v4.1.0.Windows.${{ matrix.architecture }}.zip
        path: ${{ github.workspace }}\build\source\Eyes_Protection_Reminder_v4.1.0.Windows.${{ matrix.architecture }}.exe
