name: Lastest Release

on:
  push:
    branches: [test-ci-cd]

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    name: Update Release Draft
    runs-on: ubuntu-latest

    outputs:
      tag_name: ${{ create_draft_release.outputs.tag_name }}

    steps:
    - name: Create New Draft
      id: create_draft_release
      uses: release-drafter/release-drafter@v5.21.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Release.Windows.${{ matrix.architecture }}
    needs: update_release_draft
    runs-on: windows-latest
  
    strategy:
      fail-fast: false
      matrix:
        architecture: [x86, x64]
    
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Setup MSVC Developer Command Prompt
      uses: TheMrMilchmann/setup-msvc-dev@v2.0.0
      with:
        arch: ${{ matrix.architecture }}
    
    - name: Install Ninja build tool
      uses: seanmiddleditch/gha-setup-ninja@v3
      with:
        version: 1.11.1
    
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=MinSizeRel -DwxUSE_STL=ON -DwxBUILD_COMPATIBILITY="3.1" -DwxBUILD_SHARED=OFF -G"Ninja" -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl
    
    - name: Build project
      working-directory: ${{ github.workspace }}\build
      run: cmake --build . --config MinSizeRel --target EPR
    
    - name: Zip executable file
      uses: TheDoctor0/zip-release@0.6.2
      with:
        type: zip
        filename: Eyes_Protection_Reminder_${{ needs.update_release_draft.create_draft_release.outputs.tag_name }}.Windows.${{ matrix.architecture }}.zip
        path: ${{ github.workspace }}\build\source\Eyes_Protection_Reminder_${{ needs.update_release_draft.create_draft_release.outputs.tag_name }}.Windows.${{ matrix.architecture }}.exe
    
    - name: Upload built executable file
      uses: meeDamian/github-release@v2.0.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ needs.update_release_draft.create_draft_release.outputs.tag_name }}
        files: Eyes_Protection_Reminder_${{ needs.update_release_draft.create_draft_release.outputs.tag_name }}.Windows.${{ matrix.architecture }}.zip